P_TEXT = "Lorem ipsum dolor amet hammock fam blog bushwick squid palo santo normcore fingerstache asymmetrical. Woke hoodie hexagon mumblecore lo-fi wayfarers disrupt. Banh mi echo park fashion axe viral, sustainable tilde austin distillery lomo pabst kickstarter photo booth meh. Vinyl retro next level mlkshk. Roof party cloud bread post-ironic, butcher green juice hell of swag bicycle rights waistcoat farm-to-table DIY hammock hot chicken photo booth. Selfies chia narwhal venmo flexitarian four dollar toast keytar man braid paleo jean shorts man bun umami fixie thundercats. Cred YOLO meh unicorn succulents chartreuse.

	Mustache subway tile authentic, jean shorts tofu sriracha cliche schlitz venmo crucifix dreamcatcher tilde.
	Vexillologist ramps cronut irony, activated charcoal kinfolk blue bottle freegan cold-pressed hella affogato 	woke. Portland actually vape, pour-over 8-bit try-hard bicycle rights. Brunch ennui chicharrones, sriracha paleo taxidermy kickstarter truffaut subway tile freegan swag messenger bag organic helvetica pug. Asymmetrical ugh tofu succulents fashion axe ramps affogato messenger bag. Beard waistcoat iceland trust fund, mixtape kombucha organic bicycle rights poke keytar pour-over lumbersexual pickled intelligentsia health goth. Post-ironic butcher synth poke."

P_TEXT_2 = "Kickstarter paleo synth hell of you probably haven't heard of them woke church-key celiac retro tattooed leggings master cleanse affogato pop-up. Hashtag tattooed messenger bag flannel narwhal, bushwick meggings taiyaki hot chicken cliche cardigan quinoa next level sustainable pinterest. Leggings kitsch vice pabst. Cliche poke post-ironic, franzen beard mlkshk cornhole thundercats cray sartorial migas ethical. Tbh authentic small batch, blog single-origin coffee vaporware affogato pabst slow-carb four dollar toast. Polaroid church-key copper mug, chillwave microdosing chambray cliche lomo art party ramps bicycle rights. Next level tumblr organic, pour-over meditation hella pickled four dollar toast 3 wolf moon.

YOLO tousled twee kogi vinyl, woke tilde actually. Pinterest keytar blue bottle fanny pack meditation cloud bread XOXO deep v put a bird on it master cleanse. Pok pok snackwave shaman, single-origin coffee kale chips drinking vinegar sartorial activated charcoal gastropub pinterest. Small batch normcore cliche food truck venmo thundercats wolf artisan art party taxidermy roof party.

Cred jean shorts deep v cardigan tousled direct trade copper mug actually. Fanny pack tousled bushwick meh pop-up microdosing gochujang selfies cardigan kogi. Cronut +1 chia, portland taxidermy truffaut lyft. Wolf VHS tbh, mixtape dreamcatcher fingerstache pour-over hot chicken echo park. Selfies air plant next level pok pok snackwave 90's af."

